//HintName: API_Controllers_v2_MyController.g.cs
// <auto-generated/>
using Lombok.NET;

namespace API.Controllers.v2;
#nullable enable
public partial class MyController
{
    public MyController(string value)
    {
        this._value = value;
    }
}