//HintName: Test_AllArgsValueWrapper.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class AllArgsValueWrapper<T>
{
    internal AllArgsValueWrapper(T value, string text)
    {
        this.Value = value;
        this.Text = text;
    }
}