//HintName: Test_Person.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class Person
{
    internal Person(string name, int age)
    {
        this._name = name;
        this._age = age;
    }
}