//HintName: Test_AllArgsValueWrapperStruct.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class AllArgsValueWrapperStruct<T>
{
    internal AllArgsValueWrapperStruct(T value, int index)
    {
        this.Value = value;
        this.Index = index;
    }
}