//HintName: Test_ReservedKeywordPerson.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class ReservedKeywordPerson
{
    internal ReservedKeywordPerson(int @class, string @abstract, bool @int, char @void)
    {
        this._class = @class;
        this._abstract = @abstract;
        this._int = @int;
        this._void = @void;
    }
}