//HintName: Test_Person.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial struct Person
{
    internal Person(string name, int age)
    {
        this.Name = name;
        this.Age = age;
    }
}