//HintName: Test_IncorrectConventionModel.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
public partial class IncorrectConventionModel
{
    public IncorrectConventionModel(string name)
    {
        this.name = name;
    }
}