//HintName: Test_MyAsyncViewModel.Run.g.cs
// <auto-generated/>
using System;
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class MyAsyncViewModel
{
    public global::System.Threading.Tasks.Task RunAsync(int i)
    {
        Run(i);
        return global::System.Threading.Tasks.Task.CompletedTask;
    }
}