//HintName: Test_MyAsyncViewModel.IsValid.g.cs
// <auto-generated/>
using System;
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class MyAsyncViewModel
{
    public global::System.Threading.Tasks.Task<bool> IsValidAsync() => global::System.Threading.Tasks.Task.FromResult(IsValid());
}