//HintName: Test_AsyncOverloadsClass.g.cs
// <auto-generated/>
using System;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class AsyncOverloadsClass
{
    public abstract global::System.Threading.Tasks.Task RunAsync(Guid guid, global::System.Threading.CancellationToken cancellationToken = default);
    public abstract global::System.Threading.Tasks.Task<(string, int)> GetValueAsync(global::System.Threading.CancellationToken cancellationToken = default);
    public abstract global::System.Threading.Tasks.Task<DateTime> GetCurrentDateAsync(global::System.Threading.CancellationToken cancellationToken = default);
}