//HintName: Test_Beverage.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
public class BeverageDecorator : Beverage
{
    private readonly Beverage _beverage;
    public BeverageDecorator(Beverage beverage)
    {
        _beverage = beverage;
    }

    public override double GetPrice()
    {
        return _beverage.GetPrice();
    }
}