//HintName: Test_IFoo.g.cs
// <auto-generated/>
using System;
using Lombok.NET;

namespace Test;
#nullable enable
public class FooDecorator : IFoo
{
    private readonly IFoo _foo;
    public FooDecorator(IFoo foo)
    {
        _foo = foo;
    }

    public override object? GetFormat(System.Type? formatType)
    {
        return _foo.GetFormat(formatType);
    }
}