//HintName: Test_IVehicle.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
public class VehicleDecorator : IVehicle
{
    private readonly IVehicle _vehicle;
    internal VehicleDecorator(IVehicle vehicle)
    {
        _vehicle = vehicle;
    }

    public virtual void Drive()
    {
        _vehicle.Drive();
    }

    public virtual int GetNumberOfWheels()
    {
        return _vehicle.GetNumberOfWheels();
    }

    public virtual HttpStatusCode GetStatusCode()
    {
        return _vehicle.GetStatusCode();
    }
}