//HintName: Test_IFoo.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
public class FooDecorator : IFoo
{
    private readonly IFoo _foo;
    public FooDecorator(IFoo foo)
    {
        _foo = foo;
    }

    public virtual void Something()
    {
        _foo.Something();
    }

    public virtual int ReturnSomething()
    {
        return _foo.ReturnSomething();
    }
}