//HintName: Test_Foo.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
public class FooDecorator : Foo
{
    private readonly Foo _foo;
    public FooDecorator(Foo foo)
    {
        _foo = foo;
    }

    public override void Something()
    {
        _foo.Something();
    }

    public override int ReturnSomething()
    {
        return _foo.ReturnSomething();
    }
}