//HintName: Test_MyEnum.g.cs
// <auto-generated/>
namespace Test;
public static class MyEnumValues
{
    public static MyEnum[] Values { get; } =
    {
        MyEnum.One,
        MyEnum.Two,
        MyEnum.Three,
    };
}