//HintName: Test_HeavyInitialization.g.cs
// <auto-generated/>
namespace Test;
#nullable enable
internal partial class HeavyInitialization
{
    public static readonly global::System.Lazy<HeavyInitialization> Lazy = new(() => new HeavyInitialization());
}