//HintName: Test_PropertyChangedViewModel.g.cs
// <auto-generated/>
namespace Test;
#nullable enable
internal partial class PropertyChangedViewModel : global::System.ComponentModel.INotifyPropertyChanged
{
    public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
    protected void SetFieldAndRaisePropertyChanged<T>(out T field, T newValue, [global::System.Runtime.CompilerServices.CallerMemberName] string? propertyName = null)
    {
        field = newValue;
        PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));
    }
}