//HintName: Test_PropertyChangingViewModel.g.cs
// <auto-generated/>
namespace Test;
#nullable enable
internal partial class PropertyChangingViewModel : global::System.ComponentModel.INotifyPropertyChanging
{
    public event global::System.ComponentModel.PropertyChangingEventHandler? PropertyChanging;
    protected void SetFieldAndRaisePropertyChanging<T>(out T field, T newValue, [global::System.Runtime.CompilerServices.CallerMemberName] string? propertyName = null)
    {
        PropertyChanging?.Invoke(this, new global::System.ComponentModel.PropertyChangingEventArgs(propertyName));
        field = newValue;
    }
}