//HintName: Test_PropertyPersonWithComments.Height.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyPersonWithComments
{
    /// <summary>
    /// The person's height.
    /// </summary>
    public int Height { get => _height; set => _height = value; }
}