//HintName: Test_PropertyPersonWithComments.Age.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyPersonWithComments
{
    /// <summary>
    /// The person's age.
    /// </summary>
    public int Age => _age;
}