//HintName: Test_ReactivePropertyChangeViewModel.Name.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class ReactivePropertyChangeViewModel
{
    public string Name { get => _name; set => global::ReactiveUI.IReactiveObjectExtensions.RaiseAndSetIfChanged(this, ref _name, value); }
}