//HintName: Test_PropertyPerson.Name.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyPerson
{
    public string Name { get => _name; set => _name = value; }
}