//HintName: Test_PropertyPerson.Age.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyPerson
{
    public int Age => _age;
}