//HintName: Test_PropertyPersonWithComments.Name.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyPersonWithComments
{
    /*
	   * The person's name.
	   */
    public string Name { get => _name; set => _name = value; }
}