//HintName: Test_PropertyPersonWithValidationAttributes.Email.g.cs
// <auto-generated/>
using System.ComponentModel.DataAnnotations;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyPersonWithValidationAttributes
{
    [EmailAddress]
    public string Email { get => _email; set => _email = value; }
}