//HintName: Test_PropertyPersonStruct.Name.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial struct PropertyPersonStruct
{
    public string Name { get => _name; set => _name = value; }
}