//HintName: Test_PropertyPerson.StatusCode.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyPerson
{
    public HttpStatusCode StatusCode => _statusCode;
}