//HintName: Test_PropertyPersonWithComments.StatusCode.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyPersonWithComments
{
    // The person's status code.
    public HttpStatusCode StatusCode => _statusCode;
}