//HintName: Test_PropertyPersonStruct.StatusCode.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial struct PropertyPersonStruct
{
    public HttpStatusCode StatusCode => _statusCode;
}