//HintName: Test_PropertyChangedViewModel.Name.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyChangedViewModel
{
    public string Name { get => _name; set => SetFieldAndRaisePropertyChanged(out _name, value); }
}