//HintName: Test_PropertyChangingViewModel.Name.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyChangingViewModel
{
    public string Name { get => _name; set => SetFieldAndRaisePropertyChanging(out _name, value); }
}