//HintName: Test_PropertyPersonStruct.Age.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial struct PropertyPersonStruct
{
    public int Age => _age;
}