//HintName: Test_PropertyChangingViewModel.StatusCode.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyChangingViewModel
{
    public HttpStatusCode StatusCode { get => _statusCode; set => SetFieldAndRaisePropertyChanging(out _statusCode, value); }
}