//HintName: Test_PropertyChangedViewModel.StatusCode.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class PropertyChangedViewModel
{
    public HttpStatusCode StatusCode { get => _statusCode; set => SetFieldAndRaisePropertyChanged(out _statusCode, value); }
}