//HintName: Test_RequiredArgsPerson.g.cs
// <auto-generated/>
using System;
using Lombok.NET;

namespace Test;
#nullable enable
public partial class RequiredArgsPerson
{
    public RequiredArgsPerson(EventHandler @event)
    {
        this.@event = @event;
    }
}