//HintName: Test_RequiredArgsPerson.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class RequiredArgsPerson
{
    internal RequiredArgsPerson(string name)
    {
        this._name = name;
    }
}