//HintName: Test_RequiredArgsPerson.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class RequiredArgsPerson
{
    internal RequiredArgsPerson(string name, double height)
    {
        this._name = name;
        this._height = height;
    }
}