//HintName: Test_RequiredArgsPerson.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
public partial class RequiredArgsPerson
{
    public RequiredArgsPerson(string test, string test1, int value, int value2, string @string)
    {
        this.test = test;
        this.Test = test1;
        this.value = value;
        this._value = value2;
        this.@string = @string;
    }
}