//HintName: Test_RequiredArgsValueWrapper.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class RequiredArgsValueWrapper<T>
{
    internal RequiredArgsValueWrapper(T value, string text)
    {
        this.Value = value;
        this.Text = text;
    }
}