//HintName: Test_RequiredArgsPerson.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class RequiredArgsPerson
{
    internal RequiredArgsPerson(string name)
    {
        this.Name = name;
    }
}