//HintName: Test_PersonRepository.g.cs
// <auto-generated/>
namespace Test;
#nullable enable
internal partial class PersonRepository
{
    public static PersonRepository Instance => Nested.Instance;

    private class Nested
    {
        static Nested()
        {
        }

        internal static readonly PersonRepository Instance = new PersonRepository();
    }
}