//HintName: Test_Person.g.cs
// <auto-generated/>
namespace Test;
#nullable enable
internal partial struct Person
{
    public override string ToString()
    {
        return $"Person: Name={Name}; Age={Age}";
    }
}