//HintName: Test_MoodExtensions.g.cs
// <auto-generated/>
namespace Test;
#nullable enable
public static class MoodExtensions
{
    internal static string ToText(this Mood mood)
    {
        return mood switch
        {
            Mood.Happy => nameof(Mood.Happy),
            Mood.Sad => nameof(Mood.Sad),
            Mood.Mad => nameof(Mood.Mad),
            _ => throw new global::System.ArgumentOutOfRangeException(nameof(mood), mood, null)};
    }
}