//HintName: Test_Person.g.cs
// <auto-generated/>
namespace Test;
#nullable enable
internal partial class Person
{
    public override string ToString()
    {
        return $"Person: _name={_name}; _age={_age}; _password=****";
    }
}