//HintName: Test_Person.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class Person
{
    public Person WithId(int id)
    {
        this.id = id;
        return this;
    }

    public Person WithName(string name)
    {
        this.name = name;
        return this;
    }

    public Person WithS(HttpStatusCode s)
    {
        this.s = s;
        return this;
    }
}