//HintName: Test_Person.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class Person
{
    public Person WithId(int id)
    {
        this.Id = id;
        return this;
    }

    public Person WithName(string name)
    {
        this.Name = name;
        return this;
    }

    public Person WithAge(int age)
    {
        this.Age = age;
        return this;
    }
}