//HintName: Test_Person.g.cs
// <auto-generated/>
using System.Net;
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class Person
{
    public Person WithName(string name)
    {
        this.name = name;
        return this;
    }

    public Person WithRemark(string? remark)
    {
        this.remark = remark;
        return this;
    }

    public Person WithS(HttpStatusCode s)
    {
        this.s = s;
        return this;
    }

    public Person WithId(int id)
    {
        this.id = id;
        return this;
    }

    public Person WithReferencedId(int? referencedId)
    {
        this.referencedId = referencedId;
        return this;
    }

    public Person WithData(Data data)
    {
        this.data = data;
        return this;
    }

    public Person WithData2(Data? data2)
    {
        this.data2 = data2;
        return this;
    }
}