//HintName: Test_Person.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
internal partial class Person
{
    public Person WithId(int id)
    {
        this.id = id;
        return this;
    }
}