//HintName: Test_Person.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
public partial class Person
{
    public Person WithAge(int age)
    {
        this.Age = age;
        return this;
    }
}