//HintName: Test_InheritingClass.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
public partial class InheritingClass
{
    public InheritingClass WithName(string name)
    {
        this.Name = name;
        return this;
    }

    public InheritingClass WithId(int id)
    {
        this.Id = id;
        return this;
    }
}