//HintName: Test_Person.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
public partial class Person
{
    public Person WithDefault(int @default)
    {
        this.Default = @default;
        return this;
    }
}