//HintName: Test_MyClass.g.cs
// <auto-generated/>
using Lombok.NET;

namespace Test;
#nullable enable
public partial class MyClass<T>
{
    public MyClass<T> WithMyProperty(T myProperty)
    {
        this.MyProperty = myProperty;
        return this;
    }
}