name: Push actions

on:
  workflow_dispatch:
  push:
    paths:
      - 'Lombok.NET/Lombok.NET.csproj'
    branches:
      - master
        
jobs:
  nuget_push:
    name: Pushes the updated package to NuGet.
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          global-json-file: global.json
          
      - name: Run tests
        run: dotnet test Lombok.NET.Test/Lombok.NET.Test.csproj -c Release
          
      - name: Build project
        run: dotnet build Lombok.NET/Lombok.NET.csproj -c Release
        
      - name: Push package
        run: dotnet nuget push Lombok.NET/bin/Release/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json
